pub fn latex_symbols() -> &'static [(&'static str, &'static str)] {
    &[
        ("alpha", "α"),
        ("beta", "β"),
        ("gamma", "γ"),
        ("delta", "δ"),
        ("epsilon", "ϵ"),
        ("varepsilon", "ε"),
        ("zeta", "ζ"),
        ("eta", "η"),
        ("theta", "θ"),
        ("vartheta", "ϑ"),
        ("iota", "ι"),
        ("kappa", "κ"),
        ("varkappa", "ϰ"),
        ("lambda", "λ"),
        ("mu", "μ"),
        ("nu", "ν"),
        ("xi", "ξ"),
        ("pi", "π"),
        ("varpi", "ϖ"),
        ("rho", "ρ"),
        ("varrho", "ϱ"),
        ("sigma", "σ"),
        ("varsigma", "ς"),
        ("tau", "τ"),
        ("upsilon", "υ"),
        ("phi", "ϕ"),
        ("varphi", "φ"),
        ("chi", "χ"),
        ("psi", "ψ"),
        ("omega", "ω"),
        ("Gamma", "Γ"),
        ("Delta", "Δ"),
        ("Theta", "Θ"),
        ("Lambda", "Λ"),
        ("Xi", "Ξ"),
        ("Pi", "Π"),
        ("Sigma", "Σ"),
        ("Upsilon", "Υ"),
        ("Phi", "Φ"),
        ("Psi", "Ψ"),
        ("Omega", "Ω"),
        ("pm", "±"),
        ("mp", "∓"),
        ("times", "×"),
        ("div", "÷"),
        ("cdot", "·"),
        ("ast", "∗"),
        ("star", "⋆"),
        ("circ", "∘"),
        ("bullet", "•"),
        ("oplus", "⊕"),
        ("ominus", "⊖"),
        ("otimes", "⊗"),
        ("oslash", "⊘"),
        ("odot", "⊙"),
        ("bigcirc", "○"),
        ("dagger", "†"),
        ("ddagger", "‡"),
        ("amalg", "⨿"),
        ("uplus", "⊎"),
        ("sqcap", "⊓"),
        ("sqcup", "⊔"),
        ("triangleleft", "◁"),
        ("triangleright", "▷"),
        ("wr", "≀"),
        ("cap", "∩"),
        ("cup", "∪"),
        ("bigcap", "⋂"),
        ("bigcup", "⋃"),
        ("bigwedge", "⋀"),
        ("bigvee", "⋁"),
        ("bigsqcup", "⨆"),
        ("biguplus", "⨄"),
        ("bigoplus", "⨁"),
        ("bigotimes", "⨂"),
        ("bigodot", "⨀"),
        ("setminus", "∖"),
        ("in", "∈"),
        ("notin", "∉"),
        ("ni", "∋"),
        ("subset", "⊂"),
        ("supset", "⊃"),
        ("subseteq", "⊆"),
        ("supseteq", "⊇"),
        ("sqsubset", "⊏"),
        ("sqsupset", "⊐"),
        ("sqsubseteq", "⊑"),
        ("sqsupseteq", "⊒"),
        ("prec", "≺"),
        ("preceq", "≼"),
        ("succ", "≻"),
        ("succeq", "≽"),
        ("ll", "≪"),
        ("gg", "≫"),
        ("le", "≤"),
        ("leq", "≤"),
        ("leqslant", "≤"),
        ("ge", "≥"),
        ("geq", "≥"),
        ("geqslant", "≥"),
        ("ne", "≠"),
        ("neq", "≠"),
        ("equiv", "≡"),
        ("approx", "≈"),
        ("sim", "∼"),
        ("simeq", "≃"),
        ("cong", "≅"),
        ("asymp", "≍"),
        ("doteq", "≐"),
        ("propto", "∝"),
        ("parallel", "∥"),
        ("perp", "⊥"),
        ("mid", "∣"),
        ("vdash", "⊢"),
        ("dashv", "⊣"),
        ("models", "⊨"),
        ("Vdash", "⊩"),
        ("Vvdash", "⊪"),
        ("nvdash", "⊬"),
        ("nvDash", "⊭"),
        ("forall", "∀"),
        ("exists", "∃"),
        ("nexists", "∄"),
        ("neg", "¬"),
        ("land", "∧"),
        ("wedge", "∧"),
        ("lor", "∨"),
        ("vee", "∨"),
        ("to", "→"),
        ("rightarrow", "→"),
        ("longrightarrow", "→"),
        ("leftarrow", "←"),
        ("longleftarrow", "←"),
        ("gets", "←"),
        ("leftrightarrow", "↔"),
        ("longleftrightarrow", "↔"),
        ("hookleftarrow", "↩"),
        ("hookrightarrow", "↪"),
        ("twoheadleftarrow", "↞"),
        ("twoheadrightarrow", "↠"),
        ("leftharpoonup", "↼"),
        ("leftharpoondown", "↽"),
        ("rightharpoonup", "⇀"),
        ("rightharpoondown", "⇁"),
        ("rightleftharpoons", "⇌"),
        ("leftrightharpoons", "⇋"),
        ("nearrow", "↗"),
        ("searrow", "↘"),
        ("swarrow", "↙"),
        ("nwarrow", "↖"),
        ("rightsquigarrow", "⇝"),
        ("leadsto", "⇝"),
        ("Rightarrow", "⇒"),
        ("Longrightarrow", "⇒"),
        ("Leftarrow", "⇐"),
        ("Longleftarrow", "⇐"),
        ("Leftrightarrow", "⇔"),
        ("Longleftrightarrow", "⇔"),
        ("implies", "⇒"),
        ("iff", "⇔"),
        ("mapsto", "↦"),
        ("longmapsto", "↦"),
        ("uparrow", "↑"),
        ("downarrow", "↓"),
        ("partial", "∂"),
        ("nabla", "∇"),
        ("int", "∫"),
        ("iint", "∬"),
        ("iiint", "∭"),
        ("oint", "∮"),
        ("sum", "∑"),
        ("prod", "∏"),
        ("coprod", "∐"),
        ("infty", "∞"),
        ("emptyset", "∅"),
        ("varnothing", "∅"),
        ("angle", "∠"),
        ("therefore", "∴"),
        ("because", "∵"),
        ("aleph", "ℵ"),
        ("beth", "ℶ"),
        ("gimel", "ℷ"),
        ("daleth", "ℸ"),
        ("top", "⊤"),
        ("bot", "⊥"),
        ("triangle", "△"),
        ("square", "□"),
        ("lozenge", "◊"),
        ("checkmark", "✓"),
        ("complement", "∁"),
        ("wp", "℘"),
        ("prime", "′"),
        ("ldots", "…"),
        ("dots", "…"),
        ("cdots", "⋯"),
        ("vdots", "⋮"),
        ("ddots", "⋱"),
        ("ell", "ℓ"),
        ("hbar", "ℏ"),
        ("Im", "ℑ"),
        ("Re", "ℜ"),
        ("langle", "⟨"),
        ("rangle", "⟩"),
        ("vert", "|"),
        ("lvert", "|"),
        ("rvert", "|"),
        ("Vert", "‖"),
        ("lVert", "‖"),
        ("rVert", "‖"),
        ("lbrace", "{"),
        ("rbrace", "}"),
        ("backslash", "\\"),
        ("lfloor", "⌊"),
        ("rfloor", "⌋"),
        ("lceil", "⌈"),
        ("rceil", "⌉"),
        ("colon", ":"),
    ]
}
pub fn negated_symbols() -> &'static [(&'static str, &'static str)] {
    &[
        ("<", "≮"),
        (">", "≯"),
        ("=", "≠"),
        ("∈", "∉"),
        ("∋", "∌"),
        ("∣", "∤"),
        ("∥", "∦"),
        ("∼", "≁"),
        ("≃", "≄"),
        ("≅", "≇"),
        ("≈", "≉"),
        ("≡", "≢"),
        ("≤", "≰"),
        ("≥", "≱"),
        ("≺", "⊀"),
        ("≻", "⊁"),
        ("⊂", "⊄"),
        ("⊃", "⊅"),
        ("⊆", "⊈"),
        ("⊇", "⊉"),
        ("⊢", "⊬"),
        ("⊨", "⊭"),
        ("↔", "↮"),
        ("←", "↚"),
        ("→", "↛"),
        ("⇒", "⇏"),
        ("⇐", "⇍"),
        ("⇔", "⇎"),
        ("≼", "⋠"),
        ("≽", "⋡"),
    ]
}
pub fn accents() -> &'static [(&'static str, &'static str)] {
    &[
        ("acute", "́"),
        ("bar", "̅"),
        ("breve", "̆"),
        ("check", "̌"),
        ("ddot", "̈"),
        ("dot", "̇"),
        ("grave", "̀"),
        ("hat", "̂"),
        ("mathring", "̊"),
        ("overleftarrow", "⃖"),
        ("overleftrightarrow", "⃡"),
        ("overline", "̅"),
        ("overrightarrow", "⃗"),
        ("tilde", "̃"),
        ("underline", "̲"),
        ("vec", "⃗"),
        ("widehat", "̂"),
        ("widetilde", "̃"),
    ]
}
pub fn superscripts() -> &'static [(&'static str, &'static str)] {
    &[
        ("0", "⁰"),
        ("1", "¹"),
        ("2", "²"),
        ("3", "³"),
        ("4", "⁴"),
        ("5", "⁵"),
        ("6", "⁶"),
        ("7", "⁷"),
        ("8", "⁸"),
        ("9", "⁹"),
        ("+", "⁺"),
        ("-", "⁻"),
        ("=", "⁼"),
        ("(", "⁽"),
        (")", "⁾"),
        ("a", "ᵃ"),
        ("b", "ᵇ"),
        ("c", "ᶜ"),
        ("d", "ᵈ"),
        ("e", "ᵉ"),
        ("f", "ᶠ"),
        ("g", "ᵍ"),
        ("h", "ʰ"),
        ("i", "ⁱ"),
        ("j", "ʲ"),
        ("k", "ᵏ"),
        ("l", "ˡ"),
        ("m", "ᵐ"),
        ("n", "ⁿ"),
        ("o", "ᵒ"),
        ("p", "ᵖ"),
        ("r", "ʳ"),
        ("s", "ˢ"),
        ("t", "ᵗ"),
        ("u", "ᵘ"),
        ("v", "ᵛ"),
        ("w", "ʷ"),
        ("x", "ˣ"),
        ("y", "ʸ"),
        ("z", "ᶻ"),
    ]
}
pub fn subscripts() -> &'static [(&'static str, &'static str)] {
    &[
        ("0", "₀"),
        ("1", "₁"),
        ("2", "₂"),
        ("3", "₃"),
        ("4", "₄"),
        ("5", "₅"),
        ("6", "₆"),
        ("7", "₇"),
        ("8", "₈"),
        ("9", "₉"),
        ("+", "₊"),
        ("-", "₋"),
        ("=", "₌"),
        ("(", "₍"),
        (")", "₎"),
        ("a", "ₐ"),
        ("e", "ₑ"),
        ("h", "ₕ"),
        ("i", "ᵢ"),
        ("j", "ⱼ"),
        ("k", "ₖ"),
        ("l", "ₗ"),
        ("m", "ₘ"),
        ("n", "ₙ"),
        ("o", "ₒ"),
        ("p", "ₚ"),
        ("r", "ᵣ"),
        ("s", "ₛ"),
        ("t", "ₜ"),
        ("u", "ᵤ"),
        ("v", "ᵥ"),
        ("x", "ₓ"),
    ]
}
pub fn blackboard() -> &'static [(char, char)] {
    &[
        ('C', 'ℂ'),
        ('H', 'ℍ'),
        ('N', 'ℕ'),
        ('P', 'ℙ'),
        ('Q', 'ℚ'),
        ('R', 'ℝ'),
        ('Z', 'ℤ'),
    ]
}
pub fn named_operators() -> &'static [&'static str] {
    &[
        "arccos",
        "arcsin",
        "arctan",
        "arg",
        "cos",
        "cosh",
        "cot",
        "coth",
        "csc",
        "deg",
        "det",
        "dim",
        "exp",
        "gcd",
        "hom",
        "inf",
        "ker",
        "lg",
        "lim",
        "liminf",
        "limsup",
        "ln",
        "log",
        "max",
        "min",
        "Pr",
        "sec",
        "sin",
        "sinh",
        "sup",
        "tan",
        "tanh",
    ]
}
pub fn limit_operators() -> &'static [&'static str] {
    &[
        "argmax",
        "argmin",
        "inf",
        "injlim",
        "lim",
        "liminf",
        "limsup",
        "max",
        "min",
        "projlim",
        "sup",
    ]
}
pub fn display_limit_symbols() -> &'static [&'static str] {
    &[
        "bigcap",
        "bigcup",
        "bigodot",
        "bigoplus",
        "bigotimes",
        "bigsqcup",
        "biguplus",
        "bigvee",
        "bigwedge",
        "coprod",
        "int",
        "iint",
        "iiint",
        "oint",
        "prod",
        "sum",
    ]
}
pub fn relation_commands() -> &'static [&'static str] {
    &[
        "Leftarrow",
        "Leftrightarrow",
        "Longleftarrow",
        "Longleftrightarrow",
        "Longrightarrow",
        "Rightarrow",
        "Vdash",
        "Vvdash",
        "approx",
        "asymp",
        "cong",
        "dashv",
        "doteq",
        "downarrow",
        "equiv",
        "ge",
        "geq",
        "geqslant",
        "gets",
        "gg",
        "hookleftarrow",
        "hookrightarrow",
        "iff",
        "implies",
        "in",
        "leadsto",
        "le",
        "leftarrow",
        "leftharpoondown",
        "leftharpoonup",
        "leftrightarrow",
        "leftrightharpoons",
        "leq",
        "leqslant",
        "ll",
        "longleftarrow",
        "longleftrightarrow",
        "longmapsto",
        "longrightarrow",
        "mapsto",
        "mid",
        "models",
        "ne",
        "nearrow",
        "neq",
        "ni",
        "notin",
        "nvdash",
        "nvDash",
        "nwarrow",
        "parallel",
        "perp",
        "prec",
        "preceq",
        "propto",
        "rightharpoondown",
        "rightharpoonup",
        "rightleftharpoons",
        "rightarrow",
        "rightsquigarrow",
        "searrow",
        "sim",
        "simeq",
        "sqsubset",
        "sqsubseteq",
        "sqsupset",
        "sqsupseteq",
        "subset",
        "subseteq",
        "succ",
        "succeq",
        "supset",
        "supseteq",
        "swarrow",
        "to",
        "triangleleft",
        "triangleright",
        "twoheadleftarrow",
        "twoheadrightarrow",
        "uparrow",
        "vdash",
    ]
}
pub fn spacing_commands() -> &'static [&'static str] {
    &[
        ",",
        ":",
        ";",
        " ",
        ">",
        "enspace",
        "enskip",
        "medspace",
        "quad",
        "qquad",
        "thickspace",
        "thinspace",
    ]
}
pub fn negative_spacing_commands() -> &'static [&'static str] {
    &[
        "!",
        "negmedspace",
        "negthickspace",
        "negthinspace",
    ]
}
pub fn ignored_commands() -> &'static [&'static str] {
    &[
        "displaystyle",
        "limits",
        "nolimits",
        "scriptstyle",
        "scriptscriptstyle",
        "textstyle",
    ]
}
pub fn size_commands() -> &'static [&'static str] {
    &[
        "big",
        "Big",
        "bigg",
        "Bigg",
        "bigl",
        "Bigl",
        "biggl",
        "Biggl",
        "bigr",
        "Bigr",
        "biggr",
        "Biggr",
    ]
}
pub fn plain_wrappers() -> &'static [&'static str] {
    &[
        "emph",
        "mathcal",
        "mathbf",
        "mathfrak",
        "mathit",
        "mathrm",
        "mathnormal",
        "mathscr",
        "mathsf",
        "mathtt",
        "mathup",
        "mbox",
        "overbrace",
        "pmb",
        "smash",
        "substack",
        "text",
        "textbf",
        "textit",
        "textmd",
        "textnormal",
        "textrm",
        "textsc",
        "textsf",
        "textsl",
        "texttt",
        "textup",
        "underbrace",
        "bm",
        "boldsymbol",
    ]
}
