//! Transport-neutral CBOR protocol for remote pi sessions.
//!
//! Rust port of `@earendil-works/pi-protocol` (see `packages/protocol`):
//! strict definite-length RFC 8949 CBOR codec, 4-byte length-prefixed binary
//! framing, protocol message models, and validated framed encode/decode.
//!
//! Byte-identical to the JS implementation; behavior is pinned by the
//! ported unit tests (`tests/`) and byte-level differential fixtures
//! generated by `scripts/generate-protocol-fixtures.mjs`.

pub mod cbor;
pub mod codec;
pub mod framing;
pub mod schemas;

pub use cbor::{decode_cbor, encode_cbor, CborError, CborOptions, Value};
pub use codec::{
    encode_client_message, encode_server_message, is_supported_protocol_version, parse_client_message,
    parse_server_message, ClientMessageDecoder, ProtocolValidationError, ServerMessageDecoder,
    ValidatedMessageDecoder,
};
pub use framing::{assert_complete_frame, encode_frame, DEFAULT_MAX_FRAME_LENGTH, FrameDecoder, FrameError};
pub use schemas::PROTOCOL_VERSION;
